version: "3.8"

services:
  app:
   container_name: expenseTracker_app
   build:
    context: .
    dockerfile: Dockerfile
    
   ports:
    - '8081:8080'
   
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ExpenseTracker
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=Awale123
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
   depends_on:
     - db
     
  db:
   image: postgres
   container_name: db_container
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Awale123
     - POSTGRES_DB=ExpenseTracker
   ports:
      - '5433:5432'